version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: currency_gateway
    ports:
      - "5433:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # RabbitMQ
      - "15672:15672" # Management console

  app:
    build: .
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/currency_gateway
      DB_USERNAME: admin
      DB_PASSWORD: admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "8080:8080"
    command: ./mvnw spring-boot:run
